// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models;

public partial class StudInfoSysContext : DbContext
{
    public StudInfoSysContext(DbContextOptions<StudInfoSysContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Course { get; set; }

    public virtual DbSet<Room> Room { get; set; }

    public virtual DbSet<Section> Section { get; set; }

    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<Teacher> Teacher { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.Property(e => e.CourseID).ValueGeneratedNever();
            entity.Property(e => e.CourseCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("text");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.Property(e => e.RoomID).ValueGeneratedNever();
            entity.Property(e => e.Building)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoomNumber)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Section>(entity =>
        {
            entity.Property(e => e.SectionID)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Schedule)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.YearLevel)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.Property(e => e.StudentID).ValueGeneratedNever();
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MiddleInitial)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.Property(e => e.TeacherID).ValueGeneratedNever();
            entity.Property(e => e.ContactNo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}